before_script:
  - apt-get update -qq
  - apt-get install -y -qq ssh
  - apt-get install -y -qq sshpass

stages:
  - stage
  - prod

deploy_stage:
  stage: stage

  only:
    - develop

  script:
    - sshpass -p $USER_PASS ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd ${SITE_PATH}; ./deploy.sh develop"

deploy_prod:
  stage: prod

  only:
    - master

  script:
    - sshpass -p $USER_PASS ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd ${SITE_PATH}; ./deploy.sh master"
