before_script:
  - apt-get update -qq
  - apt-get install -y -qq ssh
  - apt-get install -y -qq sshpass

stages:
  - deploy

deploy_stage:
  stage: deploy

  only:
    - develop

  script:
    - sshpass -p $USER_PASS ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd ${SITE_PATH_STAGE}; ./deploy.sh develop"

deploy_prod:
  stage: deploy

  only:
    - master

  script:
    - sshpass -p $USER_PASS ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd ${SITE_PATH_PROD}; ./deploy.sh master"
